name = "aeons-info-v2"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Astro SSR 配置
main = "./dist/_worker.js/index.js"

# KV命名空间配置 - 用于Astro Cloudflare适配器的SESSION绑定
[[kv_namespaces]]
binding = "SESSION"
id = "2ee892efc54c4334b7d077c97883d55e"
preview_id = "2ee892efc54c4334b7d077c97883d55e"

[build]
command = "npm run build"

[env.production]
name = "aeons-info-v2"
