name = "aeons-info-v2"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Astro SSR 配置
main = "./dist/_worker.js/index.js"

# KV bindings (Astro Cloudflare 适配器需要 - 暂时注释掉)
# [[kv_namespaces]]
# binding = "SESSION"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"

[build]
command = "npm run build"

[env.production]
name = "aeons-info-v2"
