name = "aeons-info-v2"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Astro SSR Workers 配置
main = "./dist/_worker.js/index.js"

# 最小化KV配置 - 只保留SESSION
[[kv_namespaces]]
binding = "SESSION"
id = "2ee892efc54c4334b7d077c97883d55e"
preview_id = "2ee892efc54c4334b7d077c97883d55e"

[build]
command = "npm run build"
